routes/admin.php
<?php
//后台绑定域名
$admin_domain = env('ADMIN_URL','');
$admin_path='admin';
/*****************无需验证中间件**********************/
//无需验证权限，或者里面验证

if ($admin_domain) {

    $route = Route::domain($admin_domain);
} else {
    $route = Route::prefix($admin_path ?: '/admin/');
}

$route->middleware(['install'])->name('admin.')->group(function ($route) {
    $route->get('/login', 'LoginController@showLoginForm')->name('login');
    $route->post('login', 'LoginController@login')->name('post.login');
    $route->get('logout', 'LoginController@logout')->name('logout');
});

/*****************验证中间件**********************/
$route->middleware(['install', 'admin_auth', 'admin_check'])->name('admin.')->group(function ($route) {

    $route->get('home', 'HomeController@console')->name('home.console');
    $route->get('clear/cache', 'HomeController@clearCache')->name('home.clear.cache');
    $route->get('/', 'HomeController@index')->name('home');
    $route->get('/admin_plugin/{ename}', 'HomeController@plugin')->name('home.plugin');

    $route->any('upload/{type}', ['uses' => 'FileUploadController@handle'])->name('upload');
    $route->any('icon', ['uses' => 'IconController@index'])->name('icon');
    $route->any('error/{code}', ['uses' => 'ErrorController@index'])->name('error');
    $route->any('excel/import', ['uses' => 'ExcelController@import'])->name('excel.import');

    //增删改查存放的控制器数组
    $resource = [
        'AdminController',
        'AdminRoleController',
        'AdminPermissionController',

    ];
    if(env('OPEN_PLUGIN',1))
    {
        $resource[]='PluginController';
    }
    //需要批量操作，会注册导入导出
    $more_add_controller = [
        'AdminPermissionController',
    ];
    //只需要首页的控制器
    $only_index_controller = [
        'AdminLogController',
    ];
    //只有添加页码的控制器
    $only_add_controller = [
        'ConfigController'
    ];


    //管理员修改密码
    $route->get('admin/password', 'AdminController@password')->name("admin.password");
    $route->post('admin/password', 'AdminController@passwordPost')->name("admin.password_post");
    foreach ($resource as $c) {
        //自动获取
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $prefix_path=$controller_path;
        //插件如果绑定域名，会冲突，需要改下路径
        if(in_array($c,['PluginController'])){
            $prefix_path='adminplugin';
        }
        $route->group(['prefix' => $prefix_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");

            $route->get('create', $c . '@create')->name($controller_path . ".create");
            $route->get('show/{id}', $c . '@show')->name($controller_path . ".show");
            $route->post('store', $c . '@store')->name($controller_path . ".store");
            $route->get('edit/{id}', $c . '@edit')->name($controller_path . ".edit");
            $route->put('update/{id}', $c . '@update')->name($controller_path . ".update");
            $route->put('delete/', $c . '@destroy')->name($controller_path . ".destroy");
            $route->post('edit_list/', $c . '@editTable')->name($controller_path . ".edit_list");
        });

        $route->any($controller_path . '/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");

        //增加批量操作
        if (in_array($c, $more_add_controller)) {
            $route->get($controller_path . '/all/create', ['uses' => $c . '@allCreate'])->name($controller_path . '.all_create');
            $route->post($controller_path . '/all/create/post', ['uses' => $c . '@allCreatePost'])->name($controller_path . '.all_create_post');
        }
        //导入操作
        if (in_array($c, $more_add_controller)) {
            $route->post($controller_path . '/import/post', ['uses' => $c . '@importPost'])->name($controller_path . '.import_post');
            $route->get($controller_path . '/import/tpl', ['uses' => $c . '@importTpl'])->name($controller_path . '.import_tpl');
        }

        //额外增加
        if(in_array($c,['PluginController']))
        {
            $route->post($controller_path . '/install/{ename}/{type}', ['uses' => $c . '@install'])->name($controller_path . '.install');
        }
    }


    foreach ($only_index_controller as $c) {
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $route->group(['prefix' => $controller_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");
            $route->any('/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");
        });

    }

    foreach ($only_add_controller as $c) {
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $route->group(['prefix' => $controller_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");
            $route->post('store', $c . '@store')->name($controller_path . ".store");
            $route->any('/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");
        });

    }

});

routes/web.php
<?php
// +----------------------------------------------------------------------
// | [ Laravel快速后台开发 ]
// +----------------------------------------------------------------------
// | Copyright (c) 2012~2019 http://www.google.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: thinkpanax
// +----------------------------------------------------------------------

/*****************************************杂项路由***********************************************/
//安装
Route::prefix('thinkpanax/install')->group(function ($route) {
    $route->any('/', 'Install\IndexController@index')->name('thinkpanax.install');
    $route->any('/test', 'Install\IndexController@test')->name('thinkpanax.test');
});




//验证码
Route::prefix('api/')->group(function ($route) {
    $route->get('captcha/{type?}', 'Api\CaptchaController@index')->name('api.captcha');

});



/*****************************************END杂项路由***********************************************/



//未能匹配的路由

Route::fallback(function(){

    $route = Route::current();

    $name = Route::currentRouteName();

    $action = Route::currentRouteAction();

    return now() . ":" . request()->url() . "/ip:" . request()->ip();
    //return dd($route->getPrefix(), $action);
});

app/Http/Controllers/Install/IndexController.php
<?php

namespace App\Http\Controllers\Install;

use App\Http\Controllers\Admin\BaseController;
use Illuminate\Database\Connection;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class IndexController extends BaseController
{
    //
    public $module = 'Install';//模块名字

    public function index(Request $request)
    {


        $install_file = linux_path(storage_path()) . '/install';
        if (file_exists($install_file)) {
            //跳转到根目录
            // return redirect()->to('/');
        }

        $step = $request->input('step', '');
        if ($step) {
            $this->setModelView('step' . $step);
            $method = 'step' . $step;
            if (!in_array($step ,[4,6])) {
                $this->$method();
            }

            if ($step == 3) {
                //判断环境是否有错误，如果有则返回第二步
                if (session('install_error')) {
                    return back()->with('message', '系统检验环境不通过');
                }

            }
            if ($step == 4) {
                return $this->step4();
            }
            if ($step == 6) {
                return $this->step6();
            }

        }

        return $this->display(['index' => $step ? $step - 1 : 0]);
    }

    public function test()
    {
        //
        $a = Schema::table('vote_configs', function (Blueprint $table) {


            if (Schema::hasColumn('vote_configs', 'tongji_script2')) {
                return dump('存在了');
            }

            $table->text('tongji_script2')->nullable()->comment('统计脚本2');
        });

    }


    public function step2()
    {
        $this->shareView(['check_path' => $this->checkDirFile(), 'check_env' => $this->checkEnv(), 'ext' => $this->checkFuncExt()]);
    }

    public function step3()
    {

    }

    public function step5()
    {

    }

    public function step4()
    {
        $env_file = linux_path(base_path()) . '/.env';
        $request = request();
        $post_data = $request->all();
        $env = $this->createEnv($post_data['DB'], $post_data['REDIS'], 1);
        file_put_contents($env_file, $env);
        //跳转到第5步
        return redirect()->route('thinkpanax.install', ['step' => 6]);

    }

    public function step6()
    {
        //检验数据库
        try {
            $bd_has = DB::select(DB::raw('SHOW DATABASES LIKE "' . env('DB_DATABASE') . '"'));
            if (empty($bd_has)) {
                return back()->with('message', '数据库不存在');
            }
        } catch (\Exception $exception) {
            return back()->with('message', '数据库配置错误，请重写' . $exception->getMessage());
        }
        $db_password = env('DB_PASSWORD');

        //判断环境是否有错误，如果有则返回第二步
        //20分钟
        ini_set('max_execution_time', 60 * 20);

        //执行数据库迁移
        Artisan::call('migrate');
        //填充数据
        Artisan::call('db:seed');
        //重新生成app key
        Artisan::call('key:generate');
        //写入安装文件
        file_put_contents(linux_path(storage_path()) . '/install', date('Y-m-d H:i:s') . ' install');
        return redirect()->route('thinkpanax.install', ['step' => 5]);
    }

    public function createEnv($db, $redis, $debug = 0, $app_key = "")
    {
        $is_debug = $debug;
        $app_key = $app_key ?: "base64:Az+lvZrXmg8cJkuNNilxAZQUu48rRGYYs2rA0b2cepM=";
        $db_host = $db['DB_HOST'];
        $db_name = $db['DB_DATABASE'];
        $db_prot = $db['DB_PORT'];
        $db_user = $db['DB_USERNAME'];
        $db_password = $db['DB_PASSWORD'];
        $db_prefix = $db['DB_PREFIX'];
        $db_type = $db['DB_CONNECTION'];
        $redis_host = $redis['REDIS_HOST'];
        $redis_prot = $redis['REDIS_PORT'] ?: null;
        $redis_pwd = $redis['REDIS_PASSWORD'] ?: 6379;
        $thinkpanax_key = base64_encode(json_encode(['host' => \request()->server('SERVER_NAME'), 'ip' => \request()->server('SERVER_ADDR'), 'port' => $_SERVER['SERVER_PORT']]));

        $env = <<<EOT
APP_NAME=Laravel
APP_ENV=local
APP_KEY=$app_key
APP_DEBUG=$is_debug
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=$db_type
DB_HOST=$db_host
DB_PORT=$db_prot
DB_DATABASE=$db_name
DB_USERNAME=$db_user
DB_PASSWORD=$db_password
DB_PREFIX=$db_prefix

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=$redis_host
REDIS_PASSWORD=$redis_prot
REDIS_PORT=$redis_pwd

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

LANG=zh-CN
THINKPANAX_SERVER=$thinkpanax_key
DEBUGBAR_ENABLED=false


EOT;
        return $env;
    }

    public function viewNotControllerBlade()
    {
        return 1;
    }

    /**
     * 目录，文件读写检测
     * @return array 检测数据
     * @author jry <598821125@qq.com>
     */
    protected function checkDirFile()
    {
        $items = [
            '0' => [
                'type' => 'dir',
                'path' => storage_path(),
                'title' => '可写',
                'icon' => 'layui-icon-ok',
            ],

            '1' => [
                'type' => 'dir',
                'path' => base_path() . '/.env',
                'title' => '可写',
                'icon' => 'layui-icon-ok',
            ]

        ];

        foreach ($items as &$val) {
            $path = $val['path'];
            if ('dir' === $val['type']) {
                if (!is_writable($path)) {
                    if (is_dir($path)) {
                        $val['title'] = '不可写';
                        $val['icon'] = 'layui-icon-close text-danger';
                        session('error', true);
                    } else {
                        $val['title'] = '不存在';
                        $val['icon'] = 'layui-icon-close text-danger';
                        session('error', true);
                    }
                }
            } else {
                if (file_exists($path)) {
                    if (!is_writable($path)) {
                        $val['title'] = '不可写';
                        $val['icon'] = 'layui-icon-close text-danger';
                        session('error', true);
                    }
                } else {
                    if (!is_writable(dirname($path))) {
                        $val['title'] = '不存在';
                        $val['icon'] = 'layui-icon-close text-danger';
                        session('error', true);
                    }
                }
            }
        }
        return $items;
    }

    function checkEnv()
    {
        $items = [
            'os' => [
                'title' => '操作系统',
                'limit' => '不限制',
                'current' => PHP_OS,
                'icon' => 'layui-icon-ok text-success',
            ],
            'php' => [
                'title' => 'PHP版本',
                'limit' => '7.2.0+',
                'current' => PHP_VERSION,
                'icon' => 'layui-icon-ok text-success',
            ],
            'upload' => [
                'title' => '附件上传',
                'limit' => '不限制',
                'current' => ini_get('file_uploads') ? ini_get('upload_max_filesize') : '未知',
                'icon' => 'layui-icon-ok text-success',
            ],
            'gd' => [
                'title' => 'GD库',
                'limit' => '2.0+',
                'current' => '未知',
                'icon' => 'layui-icon-ok text-success',
            ],
            'disk' => [
                'title' => '磁盘空间',
                'limit' => '100M+',
                'current' => '未知',
                'icon' => 'layui-icon-ok text-success',
            ],
        ];

        //PHP环境检测
        if ($items['php']['current'] < 7.2) {
            $items['php']['icon'] = 'layui-icon-close text-danger';
            session('install_error', true);
        }

        //GD库检测
        $tmp = function_exists('gd_info') ? gd_info() : [];
        if (!$tmp['GD Version']) {
            $items['gd']['current'] = '未安装';
            $items['gd']['icon'] = 'layui-icon-close text-danger';
            session('error', true);
        } else {
            $items['gd']['current'] = $tmp['GD Version'];
        }
        unset($tmp);

        //磁盘空间检测
        if (function_exists('disk_free_space')) {
            $disk_size = floor(disk_free_space('./') / (1024 * 1024 * 1024)) . 'G';
            $items['disk']['current'] = $disk_size . '';
            if ($disk_size < 100) {
                $items['disk']['icon'] = 'layui-icon-close text-danger';
                session('install_error', true);
            }
        }

        return $items;
    }

    /**
     * 函数检测
     * @return array 检测数据
     */
    function checkFuncExt()
    {
        $items = [
            '0' => [
                'type' => 'ext',
                'name' => 'pdo',
                'title' => '支持',
                'current' => extension_loaded('pdo'),
                'icon' => 'layui-icon-ok text-success',
            ],
            '1' => [
                'type' => 'ext',
                'name' => 'pdo_mysql',
                'title' => '支持',
                'current' => extension_loaded('pdo_mysql'),
                'icon' => 'layui-icon-ok text-success',
            ],
            '2' => [
                'type' => 'func',
                'name' => 'file_get_contents',
                'title' => '支持',
                'icon' => 'layui-icon-ok text-success',
            ],
            '3' => [
                'type' => 'func',
                'name' => 'mb_strlen',
                'title' => '支持',
                'icon' => 'layui-icon-ok text-success',
            ]

        ];
        foreach ($items as &$val) {
            switch ($val['type']) {
                case 'ext':

resources/views/install/index.blade.php
@extends('install.layout')

@section('content')
    <div class="layui-container">
        <div class="layui-row" style="margin-top: 20px">
            <div class="layui-col-sm12">
                <div class="layui-card">
                    <div class="layui-card-header">安装协议</div>
                    <div class="layui-card-body">

                        @klang('协议')
                        <div class="" style="margin-top: 20px">
                            <a href="{{ route('thinkpanax.install',['step'=>2]) }}" class="btn layui-btn">同意安装协议</a>
                            <a href="{{ url('/') }}" class="btn layui-btn  layui-btn-primary">不同意</a>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="layui-footer footer footer-index">

            <p>© 2019 <a href="//@thinkpanax('domain')">@thinkpanax('author')</a> MIT license</p>


    </div>


@endsection

resources/views/install/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>安装 Laravel Quick Admin快速后台开发</title>
    <link rel="stylesheet" href="{{ ___('/layui/css/layui.css') }}">
    <script src="{{ ___('/layui/layui.js') }}"></script>
    @yield('add_css')
    <style>
        .header {
            height: 59px;
            border-bottom: 1px solid #404553;
            background-color: #393D49;
        }

        .logo {

            margin: 10px;
            margin-top: 18px;

        }

        .logo img {
            width: 82px;

        }

        .header .layui-nav {
            float: left;
            right: 0;
            top: 0;
            padding: 0;
            background: none;
        }

        body {
            background-color: #f6f6f6;
        }

        caption {
            padding-top: 8px;
            padding-bottom: 8px;
            color: #777;
            text-align: left;
            font-size: 16px;
        }

        .text-danger {
            color: #FF00FF;
        }

        .footer {
            padding: 30px 0;
            line-height: 30px;
            text-align: center;
            color: #666;
            font-weight: 300;
            text-align: center;
        }

        .layui-main {
            display: flex;
            display: -webkit-flex;
        }

        .install_ok_btn {
            margin-top: 50px;
        }

        @media screen and (max-width: 768px) {
            .layui-main {
                width: 100%;
            }

            .layui-nav .layui-nav-item a {
                padding: 0 6px;
            }
        }

        .table-responsive {
            min-height: .01%;
            overflow-x: auto;
        }

        @media screen and (max-width: 768px) {
            .table-responsive {
                width: 100%;
                margin-bottom: 15px;
                overflow-y: hidden;
                -ms-overflow-style: -ms-autohiding-scrollbar;
            }
        }
    </style>
</head>
<body>
@section('nav')
    @include('install.nav')
@show



@yield('content')
<script>
    //注意：导航 依赖 element 模块，否则无法进行功能性操作
    layui.use('element', function () {
        var element = layui.element;

        //…
    });
</script>
@yield('foot_js')
</body>
</html>

resources/views/install/nav.blade.php
<div class="layui-header header header-index">
    <div class="layui-main">
        <a class="logo" href="/">
            <img src="{{ ___('/install/logo.png') }}" alt="layui">
        </a>


        <ul class="layui-nav">
            @if(!empty($nav=config('copyright.installs')))
                @foreach($nav as $k=>$v)
                    <li class="layui-nav-item {{ $k==$index?'layui-nav-itemed':'' }}">
                        <a href="javascript:void(0)">{{ $v }}</a>
                    </li>
                    @endforeach
            @endif



        </ul>
        <div class="layui-nav">
            <li class="layui-nav-item ">
                <a href="//@thinkpanax('domain')" target="_blank">官网</a>
            </li>
        </div>
    </div>

</div>

resources/views/install/step2.blade.php
@extends('install.layout')

@section('content')
    <div class="layui-container">
        <div class="layui-row" style="margin-top: 20px">
            <div class="layui-col-sm12">
                <div class="layui-card">
                    <div class="layui-card-header">@klang('环境检测')</div>
                    <div class="layui-card-body">
                        <div class="table-responsive">

                            <table class="layui-table table table-hover">
                                <caption><h4>@klang('运行环境检查')</h4></caption>
                                <thead>
                                <tr>
                                    <th>目录/文件</th>
                                    <th>所需状态</th>
                                    <th>当前状态</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($check_path as $k=>$item)
                                    <tr>
                                        <td>{{ $item['path'] }}</td>
                                        <td>可写</td>
                                        <td>{{$item['title']}} <i class="layui-icon {{$item['icon']}}"></i></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <present name="check_dirfile">
                            <table class="layui-table table table-hover">
                                <caption><h4>运行环境检查</h4></caption>
                                <thead>
                                <tr>
                                    <th>项目</th>
                                    <th>所需配置</th>
                                    <th>当前配置</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($check_env as $k=>$item)
                                    <tr>
                                        <td>{{$item['title'] }}</td>
                                        <td><i class="layui-icon layui-icon-ok text-success"></i> {{ $item['limit'] }}
                                        </td>
                                        <td><i class="layui-icon {{$item['icon']}}"></i> {{$item['current'] }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </present>
                        <table class="layui-table table table-hover">
                            <caption><h4>函数及扩展依赖性检查</h4></caption>
                            <thead>
                            <tr>
                                <th>名称</th>
                                <th>检查结果</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($ext as $k=>$item)
                                <tr>
                                    <td>{{$item['name']}}</td>
                                    <td><i class="layui-icon {{$item['icon']}}"></i> {{$item['title']}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <a class="layui-btn  " href="{{ route('thinkpanax.install',['step'=>3]) }}">下一步</a>
                        <a class="layui-btn layui-btn-primary" href="{{ route('thinkpanax.install') }}">上一步</a>

                    </div>

                </div>
            </div>
        </div>
    </div>


@endsection

@section('foot_js')

    @if (session('message'))
        <script>
            layui.use('layer', function () {
                let layer = layui.layer;
                layer.msg("{{ session('message') }}")
            })
        </script>
    @endif

@endsection

resources/views/install/step5.blade.php
@extends('install.layout')

@section('content')
    <div class="layui-container">
        <div class="layui-row" style="margin-top: 20px">
            <div class="layui-col-sm12">
                <div class="layui-card">
                    <div class="layui-card-header">安装完成</div>
                    <div class="layui-card-body" style="text-align: center;min-height: 500px">

                        <h2 style="margin: 30px;text-align: center">恭喜您，<span class="" style="color: #009688">@thinkpanax('system_name')</span>
                            安装完成！</h2>


                        <blockquote >后台管理员用户名 <span style="color: #009688">manager</span> 密码默认均为 <span style="color: #009688">qwe123456</span>，请尽快登录系统进行修改，防止系统被恶意攻击。</blockquote>

                        <div class="install_ok_btn">
                            <a class="layui-btn layui-btn-primary" target="_blank" href="{{ route('admin.login') }}">登录后台</a>
                            <a class="layui-btn layui-btn-normal" target="_blank" href="/">访问首页</a>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>


@endsection

@section('foot_js')


    <script>
        layui.use(['layer', 'form'], function () {
            var form = layui.form;
            //监听提交
            form.on('submit(setDb)', function (data) {
                console.log(data.field);
                return true;
            });
        })
    </script>


@endsection