routes/admin.php
<?php
//后台绑定域名
$admin_domain = env('ADMIN_URL','');
$admin_path='admin';
/*****************无需验证中间件**********************/
//无需验证权限，或者里面验证

if ($admin_domain) {

    $route = Route::domain($admin_domain);
} else {
    $route = Route::prefix($admin_path ?: '/admin/');
}

$route->middleware(['install'])->name('admin.')->group(function ($route) {
    $route->get('/login', 'LoginController@showLoginForm')->name('login');
    $route->post('login', 'LoginController@login')->name('post.login');
    $route->get('logout', 'LoginController@logout')->name('logout');
});

/*****************验证中间件**********************/
$route->middleware(['install', 'admin_auth', 'admin_check'])->name('admin.')->group(function ($route) {

    $route->get('home', 'HomeController@console')->name('home.console');
    $route->get('clear/cache', 'HomeController@clearCache')->name('home.clear.cache');
    $route->get('/', 'HomeController@index')->name('home');
    $route->get('/admin_plugin/{ename}', 'HomeController@plugin')->name('home.plugin');

    $route->any('upload/{type}', ['uses' => 'FileUploadController@handle'])->name('upload');
    $route->any('icon', ['uses' => 'IconController@index'])->name('icon');
    $route->any('error/{code}', ['uses' => 'ErrorController@index'])->name('error');
    $route->any('excel/import', ['uses' => 'ExcelController@import'])->name('excel.import');

    //增删改查存放的控制器数组
    $resource = [
        'AdminController',
        'AdminRoleController',
        'AdminPermissionController',

    ];
    if(env('OPEN_PLUGIN',1))
    {
        $resource[]='PluginController';
    }
    //需要批量操作，会注册导入导出
    $more_add_controller = [
        'AdminPermissionController',
    ];
    //只需要首页的控制器
    $only_index_controller = [
        'AdminLogController',
    ];
    //只有添加页码的控制器
    $only_add_controller = [
        'ConfigController'
    ];


    //管理员修改密码
    $route->get('admin/password', 'AdminController@password')->name("admin.password");
    $route->post('admin/password', 'AdminController@passwordPost')->name("admin.password_post");
    foreach ($resource as $c) {
        //自动获取
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $prefix_path=$controller_path;
        //插件如果绑定域名，会冲突，需要改下路径
        if(in_array($c,['PluginController'])){
            $prefix_path='adminplugin';
        }
        $route->group(['prefix' => $prefix_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");

            $route->get('create', $c . '@create')->name($controller_path . ".create");
            $route->get('show/{id}', $c . '@show')->name($controller_path . ".show");
            $route->post('store', $c . '@store')->name($controller_path . ".store");
            $route->get('edit/{id}', $c . '@edit')->name($controller_path . ".edit");
            $route->put('update/{id}', $c . '@update')->name($controller_path . ".update");
            $route->put('delete/', $c . '@destroy')->name($controller_path . ".destroy");
            $route->post('edit_list/', $c . '@editTable')->name($controller_path . ".edit_list");
        });

        $route->any($controller_path . '/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");

        //增加批量操作
        if (in_array($c, $more_add_controller)) {
            $route->get($controller_path . '/all/create', ['uses' => $c . '@allCreate'])->name($controller_path . '.all_create');
            $route->post($controller_path . '/all/create/post', ['uses' => $c . '@allCreatePost'])->name($controller_path . '.all_create_post');
        }
        //导入操作
        if (in_array($c, $more_add_controller)) {
            $route->post($controller_path . '/import/post', ['uses' => $c . '@importPost'])->name($controller_path . '.import_post');
            $route->get($controller_path . '/import/tpl', ['uses' => $c . '@importTpl'])->name($controller_path . '.import_tpl');
        }

        //额外增加
        if(in_array($c,['PluginController']))
        {
            $route->post($controller_path . '/install/{ename}/{type}', ['uses' => $c . '@install'])->name($controller_path . '.install');
        }
    }


    foreach ($only_index_controller as $c) {
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $route->group(['prefix' => $controller_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");
            $route->any('/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");
        });

    }

    foreach ($only_add_controller as $c) {
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $route->group(['prefix' => $controller_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");
            $route->post('store', $c . '@store')->name($controller_path . ".store");
            $route->any('/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");
        });

    }

});

routes/web.php
<?php
// +----------------------------------------------------------------------
// | [ Laravel快速后台开发 ]
// +----------------------------------------------------------------------
// | Copyright (c) 2012~2019 http://www.google.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: thinkpanax
// +----------------------------------------------------------------------

/*****************************************杂项路由***********************************************/
//安装
Route::prefix('thinkpanax/install')->group(function ($route) {
    $route->any('/', 'Install\IndexController@index')->name('thinkpanax.install');
    $route->any('/test', 'Install\IndexController@test')->name('thinkpanax.test');
});




//验证码
Route::prefix('api/')->group(function ($route) {
    $route->get('captcha/{type?}', 'Api\CaptchaController@index')->name('api.captcha');

});



/*****************************************END杂项路由***********************************************/



//未能匹配的路由

Route::fallback(function(){

    $route = Route::current();

    $name = Route::currentRouteName();

    $action = Route::currentRouteAction();

    return now() . ":" . request()->url() . "/ip:" . request()->ip();
    //return dd($route->getPrefix(), $action);
});

app/Http/Controllers/Admin/LoginController.php
<?php

namespace App\Http\Controllers\Admin;


use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Validator;
use URL;
use Illuminate\Support\Facades\Redis;

class LoginController extends BaseController
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality tvalidatorFormo your applications.
    |
    */
    use AuthenticatesUsers;
    /**
     * Where to redirect users after login.
     *
     * @var string
     */

    public function username()
    {
        return 'account';
    }

    protected function guard()
    {
        return Auth::guard('admin');
    }

    /**
     * 登录失败
     * @param Request $request
     * @return array
     */
    protected function sendFailedLoginResponse(Request $request)
    {
        return ([ 'code' => 1, 'msg' => '会员或密码错误']);
    }



    protected function formError($error)
    {
        $error = $error->all();
        if (count($error) <= 0) return [];
        $error_str = '';
        foreach ($error as $k => $v) {
            $error_str .= $v . "*<br/>";
        }
        return response()->json([ 'code' => 1, 'msg' => $error_str]);
    }

    /**
     * 登录成功
     * @return \Illuminate\Http\JsonResponse
     */
    public function authenticated()
    {
        //更新session_key
        $admin = admin();
        $admin->session_token = Session::getId();
        $admin->last_ip = \request()->getClientIp();
        $admin->login_numbers += 1;
        $admin->save();
        $back_url = '';
        $url = route('admin.home');
        return response()->json(['code' => 200, 'msg' => '登录成功', 'data' => $url]);
    }

    /**
     * 登录页面
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showLoginForm()
    {

        return $this->display();
    }

    protected function validatorForm($request)
    {
        $message_data = [
            $this->username() . '.required' => '请输入账号',
            'password.required' => '请输入密码',
        ];
        $check_data =
            [
                $this->username() => 'required|string',
                'password' => 'required|string',
                'captcha' => 'required|captcha'
            ];
        $validator = Validator::make($request->all(), $check_data, $message_data);
        if ($validator->fails()) {
            if ($request->ajax() || $request->wantsJson()) {
                return $validator->errors();
            }
        }
        return [];
    }

    protected function sendLockoutResponse(Request $request)
    {
        $seconds = $this->limiter()->availableIn(
            $this->throttleKey($request)
        );
        return response()->json(['error' => 1, 'msg' => '登陆失败次数过多，请'.$seconds.'秒后再重试'  ]);
    }

    public function login(Request $request)
    {
        $error = $this->validatorForm($request);
        if (count($error) > 0) {
            return $this->formError($error);
        };
        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        //确定用户是否有太多失败的登录尝试。
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);
            //太多次返回的信息
            return $this->sendLockoutResponse($request);
        }
        if ($this->attemptLogin($request)) {
            //通过之后响应
            return $this->sendLoginResponse($request);
        }
        //增加登陆尝试次数，默认尝试增加1次
        $this->incrementLoginAttempts($request);
        return $this->sendFailedLoginResponse($request);
    }

    public function logout(Request $request)
    {
        $this->guard()->logout();
        $request->session()->invalidate();
        return $this->loggedOut($request) ?: redirect()->route('admin.login');
    }
}

resources/views/admin/login/showloginform.blade.php
@extends('admin.layout.base')
@section('add_css')
    <link rel="stylesheet" href="{{___('/admin/style/login.css')}}">
    <script>
        //登录页面在iframe下进行修复，新建打开
        if(top.location!=self.location){
            parent.window.location.reload();
        }
    </script>
@endsection
@section('content')
    <div class="layadmin-user-login layadmin-user-display-show" id="LAY-user-login">

        <div class="layadmin-user-login-main">
            <div class="layadmin-user-login-box layadmin-user-login-header">
                <h2>@thinkpanax('system_name')</h2>

            </div>
            <div class="layadmin-user-login-box layadmin-user-login-body layui-form">
                @csrf
                <div class="layui-form-item">
                    <label class="layadmin-user-login-icon layui-icon layui-icon-username"
                           for="LAY-user-login-username"></label>
                    <input type="text" name="account" id="LAY-user-login-username" lay-verify="required"
                           placeholder="用户名" class="layui-input">
                </div>
                <div class="layui-form-item">
                    <label class="layadmin-user-login-icon layui-icon layui-icon-password"
                           for="LAY-user-login-password"></label>
                    <input type="password" name="password" id="LAY-user-login-password" lay-verify="required"
                           placeholder="密码" class="layui-input">
                </div>
                <div class="layui-form-item">
                    <div class="layui-row">
                        <div class="layui-col-xs7">
                            <label class="layadmin-user-login-icon layui-icon layui-icon-vercode"
                                   for="LAY-user-login-vercode"></label>
                            <input type="text" name="captcha" id="LAY-user-login-vercode" lay-verify="required"
                                   placeholder="图形验证码" class="layui-input">
                        </div>
                        <div class="layui-col-xs5">
                            <div style="margin-left: 10px;">
                                <img src="{{ route('api.captcha',['type'=>3]) }}"
                                     data-src="{{ route('api.captcha',['type'=>3]) }}"
                                     class="layadmin-user-login-codeimg" id="LAY-user-get-vercode">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item" style="margin-bottom: 20px;">
                    <input type="checkbox" name="remember" lay-skin="primary" title="记住密码">

                </div>
                <div class="layui-form-item">
                    <button class="layui-btn layui-btn-fluid" lay-submit lay-filter="LAY-user-login-submit">登 入</button>
                </div>

            </div>
        </div>

        <div class="layui-trans layadmin-user-login-footer">

            <p>© 2012-{{ date('Y') }} </p>

        </div>


    </div>

@endsection
@section('foot_js')
    <script>

        var postLoginUrl = '{{ route('admin.post.login') }}';

        layui.use([ 'index','form', 'verify','request'], function () {

            var $ = layui.$
                , request = layui.request
                , form = layui.form
                , layer = layui.layer;
            form.render();
            //提交
            form.on('submit(LAY-user-login-submit)', function (obj) {
                request.post(postLoginUrl, obj.field, function (res) {
                    if (res.code != 200) {
                        layer.msg(res.msg, {icon: 5, shift: 6});
                        //刷新验证码
                        $("#LAY-user-get-vercode").click();
                    }else
                    {
                        layer.msg(res.msg, {icon: 1, shift: 6});
                        location.href = res.data; //后台主页
                    }
                })

            });

            //更换图形验证码
            $("body").on('click', '#LAY-user-get-vercode', function () {
                var othis = $(this);
                this.src = othis.data('src') + '?t=' + new Date().getTime()
            });

        })
    </script>
@endsection