routes/admin.php
<?php
//后台绑定域名
$admin_domain = env('ADMIN_URL','');
$admin_path='admin';
/*****************无需验证中间件**********************/
//无需验证权限，或者里面验证

if ($admin_domain) {

    $route = Route::domain($admin_domain);
} else {
    $route = Route::prefix($admin_path ?: '/admin/');
}

$route->middleware(['install'])->name('admin.')->group(function ($route) {
    $route->get('/login', 'LoginController@showLoginForm')->name('login');
    $route->post('login', 'LoginController@login')->name('post.login');
    $route->get('logout', 'LoginController@logout')->name('logout');
});

/*****************验证中间件**********************/
$route->middleware(['install', 'admin_auth', 'admin_check'])->name('admin.')->group(function ($route) {

    $route->get('home', 'HomeController@console')->name('home.console');
    $route->get('clear/cache', 'HomeController@clearCache')->name('home.clear.cache');
    $route->get('/', 'HomeController@index')->name('home');
    $route->get('/admin_plugin/{ename}', 'HomeController@plugin')->name('home.plugin');

    $route->any('upload/{type}', ['uses' => 'FileUploadController@handle'])->name('upload');
    $route->any('icon', ['uses' => 'IconController@index'])->name('icon');
    $route->any('error/{code}', ['uses' => 'ErrorController@index'])->name('error');
    $route->any('excel/import', ['uses' => 'ExcelController@import'])->name('excel.import');

    //增删改查存放的控制器数组
    $resource = [
        'AdminController',
        'AdminRoleController',
        'AdminPermissionController',

    ];
    if(env('OPEN_PLUGIN',1))
    {
        $resource[]='PluginController';
    }
    //需要批量操作，会注册导入导出
    $more_add_controller = [
        'AdminPermissionController',
    ];
    //只需要首页的控制器
    $only_index_controller = [
        'AdminLogController',
    ];
    //只有添加页码的控制器
    $only_add_controller = [
        'ConfigController'
    ];


    //管理员修改密码
    $route->get('admin/password', 'AdminController@password')->name("admin.password");
    $route->post('admin/password', 'AdminController@passwordPost')->name("admin.password_post");
    foreach ($resource as $c) {
        //自动获取
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $prefix_path=$controller_path;
        //插件如果绑定域名，会冲突，需要改下路径
        if(in_array($c,['PluginController'])){
            $prefix_path='adminplugin';
        }
        $route->group(['prefix' => $prefix_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");

            $route->get('create', $c . '@create')->name($controller_path . ".create");
            $route->get('show/{id}', $c . '@show')->name($controller_path . ".show");
            $route->post('store', $c . '@store')->name($controller_path . ".store");
            $route->get('edit/{id}', $c . '@edit')->name($controller_path . ".edit");
            $route->put('update/{id}', $c . '@update')->name($controller_path . ".update");
            $route->put('delete/', $c . '@destroy')->name($controller_path . ".destroy");
            $route->post('edit_list/', $c . '@editTable')->name($controller_path . ".edit_list");
        });

        $route->any($controller_path . '/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");

        //增加批量操作
        if (in_array($c, $more_add_controller)) {
            $route->get($controller_path . '/all/create', ['uses' => $c . '@allCreate'])->name($controller_path . '.all_create');
            $route->post($controller_path . '/all/create/post', ['uses' => $c . '@allCreatePost'])->name($controller_path . '.all_create_post');
        }
        //导入操作
        if (in_array($c, $more_add_controller)) {
            $route->post($controller_path . '/import/post', ['uses' => $c . '@importPost'])->name($controller_path . '.import_post');
            $route->get($controller_path . '/import/tpl', ['uses' => $c . '@importTpl'])->name($controller_path . '.import_tpl');
        }

        //额外增加
        if(in_array($c,['PluginController']))
        {
            $route->post($controller_path . '/install/{ename}/{type}', ['uses' => $c . '@install'])->name($controller_path . '.install');
        }
    }


    foreach ($only_index_controller as $c) {
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $route->group(['prefix' => $controller_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");
            $route->any('/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");
        });

    }

    foreach ($only_add_controller as $c) {
        $controller = str_replace('Controller', '', $c);
        $controller_path = strtolower($controller);
        $route->group(['prefix' => $controller_path . '/'], function ($route) use ($c, $controller_path) {
            $route->get('/', $c . '@index')->name($controller_path . ".index");
            $route->post('store', $c . '@store')->name($controller_path . ".store");
            $route->any('/list', ['uses' => $c . '@getList'])->name($controller_path . ".list");
        });

    }

});

routes/web.php
<?php
// +----------------------------------------------------------------------
// | [ Laravel快速后台开发 ]
// +----------------------------------------------------------------------
// | Copyright (c) 2012~2019 http://www.google.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: thinkpanax
// +----------------------------------------------------------------------

/*****************************************杂项路由***********************************************/
//安装
Route::prefix('thinkpanax/install')->group(function ($route) {
    $route->any('/', 'Install\IndexController@index')->name('thinkpanax.install');
    $route->any('/test', 'Install\IndexController@test')->name('thinkpanax.test');
});




//验证码
Route::prefix('api/')->group(function ($route) {
    $route->get('captcha/{type?}', 'Api\CaptchaController@index')->name('api.captcha');

});



/*****************************************END杂项路由***********************************************/



//未能匹配的路由

Route::fallback(function(){

    $route = Route::current();

    $name = Route::currentRouteName();

    $action = Route::currentRouteAction();

    return now() . ":" . request()->url() . "/ip:" . request()->ip();
    //return dd($route->getPrefix(), $action);
});

app/Http/Controllers/Admin/FileUploadController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\File;
use App\Models\FileGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ExtendClass\UploadFile;
use Illuminate\Support\Facades\Storage;

class FileUploadController extends BaseController
{
    //
    public function handle($type, Request $request)
    {
        if ($type == 'upload') {
            return $this->upload($request);
        }
        if ($type == 'list') {
            return $this->getList($request);
        }
        if ($type == 'files') {
            //图片空间
            $this->setModelControllerView('fileupload');
            return $this->getList($request);
        }
        if ($type == 'api') {
            return $this->getApi($request);
        }
        if ($type == 'addGroup') {
            return $this->addGroup($request);
        }
        if ($type == 'getGroup') {
            return $this->getGroup($request);
        }
    }

    public function getGroup()
    {
        $list = FileGroup::get()->toArray();
        return $this->returnOkApi('请求成功', $list);
    }

    /**
     * 添加分组
     * @param Request $request
     * @return array|\Illuminate\Http\JsonResponse
     */
    public function addGroup(Request $request)
    {
        $name = $request->input('name');

        $error = $this->checkForm($request->all(), ['name' => 'required|unique:file_groups,name']);

        if (count($error) > 0) {
            return $this->checkFormErrorFormat($error);
        };
        $data = [
            'name' => $name,
            'model_id' => admin('id'),
            'model_type' => 'admin'
        ];

        $r = FileGroup::create($data);
        if ($r) {
            return $this->returnOkApi('添加成功', $r->id);
        }
        return $this->returnErrorApi('添加失败');
    }

    protected function upload($request)
    {
        $files = $request->input('files', 'file');
        $screen = $request->input('screen', '');
        $type = $request->input('uptype', 'image');
        $group_id = $request->input('group_id', '0');
        $method = $request->input('method', 'upload');
        $r = UploadFile::upload($files, $type, $method, $screen, $group_id);
        return response()->json($r);
    }

    protected function getList($request)
    {
        return $this->display([]);
    }

    protected function getApi($request)
    {
        $type = $request->input('uptype', '');
        $screen = $request->input('screen', '');
        $is_oss = $request->input('is_oss', false);
        $offset = $request->input('offset', 1);
        $pagesize = $request->input('limit', 1);
        $offset = ($offset - 1) * $pagesize;
        $key = $request->input('search', '');

        $model = new File();
        if ($type) {
            if ($type == 'file') {
                $model = $model->whereIn('type', ['file', 'zip', 'excel','vedio']);
            } else {
                $model = $model->where('type', $type);
            }

        }

        if ($screen) {
            $model = $model->where('screen', $screen);
        }
        $total = $model->where('user_type', 'admin')->count();

        $data = $model->where('user_type', 'admin')->skip($offset)->take($pagesize)->orderBy('id', 'desc')->get()->toArray();
        $str = '';
        $uindex = 0;
        foreach ($data as $key => $v) {
            $pic_url = $v['path'];
            $is_oss = $is_oss ? $is_oss : config('website.is_oss');
            $v['oss'] = '';
            if ($is_oss) {
                if (Storage::exists($pic_url)) {
                    $pic_url = Storage::url($v['path']);
                    $v['oss'] = Storage::url($v['path']);
                }

            }
            $img_pic = ($v['path']);
            if (in_array($v['ext'], ['.xlsx', '.xls'])) {
                $img_pic = 'excel.jpg';
                $img_pic = ___('/admin/images/' . $img_pic);
            }
            if (in_array($v['ext'], ['.doc', '.docx'])) {
                $img_pic = 'word.jpg';
                $img_pic = ___('/admin/images/' . $img_pic);
            }
            if (in_array($v['ext'], ['zip', ".rar", ".zip", ".tar", ".gz", ".7z", ".bz2"])) {
                $img_pic = 'zip.jpg';
                $img_pic = ___('/admin/images/' . $img_pic);
            }
            if (in_array($v['ext'], ['zip', ".rar", ".zip", ".tar", ".gz", ".7z", ".bz2"])) {
                $img_pic = 'zip.jpg';
                $img_pic = ___('/admin/images/' . $img_pic);
            }
            if (in_array($v['ext'], [
                ".flv", ".swf", ".mkv", ".avi", ".rm", ".rmvb", ".mpeg", ".mpg", ".wmv",
                ".ogg", ".ogv", ".mov", ".wmv", ".mp4", ".webm", ".mp3", ".wav", ".mid", ".cab", ".iso",
                ".ppt", ".pptx", ".pdf", ".txt", ".md", ".xml", ".psd", ".ai", ".cdr"
            ])) {
                $img_pic = 'file.jpg';
                $img_pic = ___('/admin/images/' . $img_pic);
            }

            $img_html = ' <img data-path="' . $pic_url . '" data-view_src="' . $img_pic . '"  data-tmpname="' . $v['tmp'] . '" data-oss="' . $v['oss_type'] . '" data-ext="' . $v['ext'] . '"  data-type="' . $v['type'] . '" src="' . $img_pic . '" class="upload-item-pic" title="' . $v['tmp'] . '" alt="" > ';
            if ($v['type'] == 'vedio') {
                $img_html = ' <video  class="upload_img" src="' . $v['path'] . '" data-type="' . $v['type'] . '" data-src="' . $v['path'] . '" controls="controls"  style="width: 100%;"></video>';
            }

            $str .= ' 
                    <div class="item item2 layui-col-xs4 layui-col-sm3 layui-col-md2 tupload-item upload-item-more "> 
                   ' . $img_html . '
                    <div class="item-foot-tools"> <p>' . $v['tmp'] . '</p> 
                    </div> </div>';
            $uindex++;
        }

        $list = [
            'total' => $total,
            'contents' => $str,
            'pagesize' => $pagesize
        ];
        $debug = $request->input('debug', 0);
        if ($debug) {
            return $this->jsonDebug($list);
        }
        return response()->json($list);
    }
}

resources/views/admin/fileupload/files.blade.php
@extends('admin.layout.baseDoing')
@section('add_css')

@endsection
@section('content')
    <div class="m-10">
        <div class="layui-breadcrumb" lay-separator="|">
            <span class="m-r-10">分类:</span>
            <a href="">默认</a>

        </div>
        <div class="m-t-10" style="">
            <div class=" tuku-list layui-uploads-pic layui-row layui-col-space10">


            </div>
            <div class="" id="page"></div>

        </div>
    </div>
@endsection
@section('foot_js')
    <script>
        var is_more="{{ request()->input('is_more',0) }}"
        layui.use(['index', 'listTable'], function () {
            var listTable = layui.listTable;
            var $=layui.$;
            listTable.diy_list(".tuku-list", "{!!  admin_url('FileUpload','handle',['type'=>'api','uptype'=>request()->input('type'),'screen'=>request()->input('screen')])  !!}", {'limit': 20});
            $(document).on('click',".upload-item-more",function(){

                if(is_more==1)
                {
                    $(this).toggleClass('on');
                }else
                {

                    $(".upload-item-more").removeClass('on');
                    $(this).addClass('on');
                }
            })
        })
    </script>
@endsection

resources/views/admin/fileupload/fileupload.blade.php
@extends('admin.layout.baseDoing')
@section('add_css')
    <style>
        .upload-category {
            margin-top: 20px;
        }
    </style>
@endsection
@section('content')
    @php
        $open_file=request()->input('open_file',0);
    @endphp
    <div class="m-10">
        <div class="layui-row layui-col-space10">

            <div class="layui-col-xs12">
                <div class="layui-tab layui-tab-brief" lay-filter="upload">
                    <ul class="layui-tab-title">
                        <li class="{{$open_file?'':'layui-this'}}">上传</li>
                        <li class="{{$open_file?'layui-this':''}}">文件库</li>

                    </ul>
                    <div class="layui-tab-content">
                        <div class="layui-tab-item layui-tab-item2 {{$open_file?'':'layui-show'}} upload-tuku-area">
                            <div class="layui-uploads-pic  ">
                                <div class=" ">
                                    <a class="pic-add pic-add2" id="upload-area" href="javascript:void(0)" data-type="{{ request()->input('type','image') }}"
                                       data-screen_type=""
                                       title="点击上传"></a>

                                </div>
                            </div>
                            <div class="upload-category">
                                <form class="layui-form" action="">
                                    <div class="layui-form-item">
                                        <label class="layui-form-label text-left">存入所属组</label>
                                        <div class="layui-input-inline">
                                            <select lay-filter="listGroup" id="listGroup">


                                            </select>
                                        </div>
                                        <div class="layui-form-mid layui-word-aux"><a href="javascript:void(0)"
                                                                                      class="text-primary js-add">添加</a>
                                        </div>
                                    </div>
                                </form>
                                <div class="upload-categor-form layui-hide">
                                    <form class="layui-form" action="">
                                        <label class="layui-form-label text-left">名称</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="name" required lay-verify="required"
                                                   placeholder="请输入名称" autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-input-inline">
                                            <button class="layui-btn" lay-submit lay-filter="addGroup">添加</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class=" upload-tuku-list  layui-uploads-pic layui-row layui-col-space10">


                            </div>
                        </div>
                        <div class="layui-tab-item {{$open_file?'layui-show':''}}">
                            <div class=" tuku-list layui-uploads-pic layui-row layui-col-space10">


                            </div>
                            <div class="" id="page"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    </div>
@endsection
@section('foot_js')
    <script>
        var open_file="{{ request()->input('open_file',0) }}";
        var is_more = "{{ request()->input('is_more',0) }}"
        layui.use(['index', 'listTable', 'request', 'layer', 'uploader', 'element'], function () {
            var element = layui.element;
            var listTable = layui.listTable;
            var req = layui.request;
            var $ = layui.$;
            var layer = layui.layer;
            var form = layui.form;
            var is_loading_list=0;

            element.on('tab(upload)', function (data) {

                console.log(data.index); //得到当前Tab的所在下标
                if (data.index == 1) {
                    if(!is_loading_list)
                    {
                        listTable.diy_list(".tuku-list", "{!!  admin_url('FileUpload','handle',['type'=>'api','uptype'=>request()->input('type'),'screen'=>request()->input('screen')])  !!}", {'limit': 20});
                        is_loading_list=1;
                    }

                }

            });
            //如果打开文件，需要执行AJAX请求
            if(open_file)
            {
                listTable.diy_list(".tuku-list", "{!!  admin_url('FileUpload','handle',['type'=>'api','uptype'=>request()->input('type'),'screen'=>request()->input('screen')])  !!}", {'limit': 20});
                is_loading_list=1;
            }

            $(document).on('click', ".upload-item-more", function () {

                if (is_more == 1) {
                    $(this).toggleClass('on');
                } else {

                    $(".upload-item-more").removeClass('on');
                    $(this).addClass('on');
                }
            })

            var uploader = layui.uploader;
            var uploadObj;

            uploadObj = uploader.list_upload("#upload-area");

            //添加分组
            form.on('submit(addGroup)', function (data) {

                req.post('{{ route('admin.upload',['type'=>'addGroup']) }}', data.field, function (res) {
                    layui.layer.msg(res.msg);
                    if (res.code == 200) {
                        getGroup(res.data);
                        //修改分组
                        uploadObj.config.data.group_id = res.data;
                        $("#upload-area").attr('group_id', res.data);
                        $(".upload-categor-form").toggleClass('layui-hide');
                    } else {

                    }
                })
                return false;

            });

            form.on('select(listGroup)', function (data) {

                $("#upload-area").attr('group_id', data.value);
                //修改分组
                uploadObj.config.data.group_id = data.value;

            });
            getGroup();

            /**
             * 取得分组
             * @param id
             */
            function getGroup(id) {
                //请求分组
                req.post('{{ route('admin.upload',['type'=>'getGroup']) }}', {}, function (res) {

                    var html_str = '<option value="0">默认</option>';
                    var select_str = '';
                    if (res.data.length > 0) {

                        for (var i in res.data) {
                            if (res.data[i]['id'] == id) {
                                select_str = 'selected';
                            } else {
                                select_str = '';
                            }
                            html_str += '<option value="' + res.data[i]['id'] + '" ' + select_str + '>' + res.data[i]['name'] + '</option>';
                        }
                    }
                    $("#listGroup").empty().append(html_str);
                    form.render('select'); //刷新select选择框渲染
                })
            }

            $(".js-add").click(function () {
                $(".upload-categor-form").toggleClass('layui-hide');
            })


        })
    </script>
@endsection